export async function POST(request: Request) {
  const body = await request.json().catch(() => ({})) as { image?:string };
  const fallback = { category:"Tops", subcategory:"Cardigan", dominantColor:"Cream", pattern:"Solid", material:{ value:"Cotton blend", confidence:"inferred" }, warmth:3, formality:3, seasons:["Spring","Fall","Winter"], occasions:["Office","Casual"] };
  if (!body.image || process.env.NEXT_PUBLIC_DEMO_MODE === "true" || !process.env.OPENAI_API_KEY) return Response.json({ source:"demo", analysis:fallback });
  const response = await fetch("https://api.openai.com/v1/responses", { method:"POST", headers:{ Authorization:`Bearer ${process.env.OPENAI_API_KEY}`, "Content-Type":"application/json" }, body:JSON.stringify({ model:process.env.OPENAI_VISION_MODEL || "gpt-5-mini", input:[{ role:"user", content:[{ type:"input_text", text:"Analyze this single garment. Do not claim a material with certainty from appearance alone; mark it inferred." }, { type:"input_image", image_url:body.image }] }], text:{ format:{ type:"json_schema", name:"garment_analysis", strict:true, schema:{ type:"object", additionalProperties:false, properties:{ category:{type:"string"}, subcategory:{type:"string"}, dominantColor:{type:"string"}, pattern:{type:"string"}, material:{type:"object",additionalProperties:false,properties:{value:{type:"string"},confidence:{type:"string",enum:["inferred"]}},required:["value","confidence"]}, warmth:{type:"integer",minimum:1,maximum:5}, formality:{type:"integer",minimum:1,maximum:5}, seasons:{type:"array",items:{type:"string"}}, occasions:{type:"array",items:{type:"string"}} }, required:["category","subcategory","dominantColor","pattern","material","warmth","formality","seasons","occasions"] } } } }) });
  if (!response.ok) return Response.json({ source:"fallback", analysis:fallback });
  const result = await response.json() as { output_text?:string };
  return Response.json({ source:"openai", analysis:JSON.parse(result.output_text || JSON.stringify(fallback)) });
}
