import { loadGarments, loadProfile, loadWearSignals, fallbackContext } from "../../../../lib/pilot-server";
import type { ShoppingAttributes } from "../../../../lib/pilot-domain";
import { analyzeShoppingCandidate } from "../../../../lib/shopping-decision";
import { apiError, privateResponse, requireUser, unauthorized } from "../../../../lib/supabase-server";

const categories=new Set(["Tops","Bottoms","Dresses","Outerwear","Shoes"]);
function validImage(bytes:Uint8Array,type:string){if(bytes.byteLength<12)return false;if(type==="image/jpeg")return bytes[0]===0xff&&bytes[1]===0xd8;if(type==="image/png")return bytes[0]===0x89&&bytes[1]===0x50&&bytes[2]===0x4e&&bytes[3]===0x47;if(type==="image/webp")return String.fromCharCode(...bytes.slice(0,4))==="RIFF"&&String.fromCharCode(...bytes.slice(8,12))==="WEBP";return false;}
function validateAttributes(raw:Record<string,unknown>):ShoppingAttributes|null{const category=String(raw.category||"");if(!categories.has(category))return null;return{name:String(raw.name||`${raw.color||""} ${raw.subcategory||category}`).slice(0,100),category:category as ShoppingAttributes["category"],subcategory:String(raw.subcategory||category).slice(0,60),color:String(raw.color||"Neutral").slice(0,40),material:String(raw.material||"Material to confirm").slice(0,80),pattern:String(raw.pattern||"Solid").slice(0,40),silhouette:String(raw.silhouette||raw.subcategory||category).slice(0,60),formality:Math.max(1,Math.min(5,Number(raw.formality)||3)),warmth:Math.max(1,Math.min(5,Number(raw.warmth)||2)),occasions:Array.isArray(raw.occasions)?raw.occasions.map(String).slice(0,8):["Casual"],confidence:Math.max(0,Math.min(1,Number(raw.confidence)||0)),rainCompatible:Boolean(raw.rainCompatible)};}
async function vision(bytes:Uint8Array,type:string):Promise<ShoppingAttributes|null>{if(!process.env.OPENAI_API_KEY)return null;const base64=btoa(Array.from(bytes,byte=>String.fromCharCode(byte)).join(""));const schema={type:"object",additionalProperties:false,properties:{name:{type:"string"},category:{type:"string",enum:[...categories]},subcategory:{type:"string"},color:{type:"string"},material:{type:"string"},pattern:{type:"string"},silhouette:{type:"string"},formality:{type:"integer",minimum:1,maximum:5},warmth:{type:"integer",minimum:1,maximum:5},occasions:{type:"array",items:{type:"string"}},confidence:{type:"number",minimum:0,maximum:1},rainCompatible:{type:"boolean"}},required:["name","category","subcategory","color","material","pattern","silhouette","formality","warmth","occasions","confidence","rainCompatible"]};const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_VISION_MODEL||"gpt-5-mini",input:[{role:"user",content:[{type:"input_text",text:"Extract only visible product attributes from this shopping screenshot. Treat material as an estimate."},{type:"input_image",image_url:`data:${type};base64,${base64}`}]}],text:{format:{type:"json_schema",name:"shopping_item",strict:true,schema}}})});if(!response.ok)return null;const data=await response.json() as {output_text?:string};return validateAttributes(JSON.parse(data.output_text||"{}"));}

export async function POST(request:Request){
  const auth=await requireUser(request);if(!auth)return unauthorized();const contentType=request.headers.get("content-type")||"";let attributes:ShoppingAttributes|null=null;let screenshot_path:string|null=null;
  if(contentType.includes("application/json")){const body=await request.json().catch(()=>({})) as {attributes?:Record<string,unknown>};attributes=validateAttributes(body.attributes||{});}else{const form=await request.formData().catch(()=>null);const file=form?.get("screenshot");if(!(file instanceof File)||!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>10*1024*1024)return apiError("SCREENSHOT_INVALID","Use a JPEG, PNG, or WebP screenshot under 10 MB.",400);const bytes=new Uint8Array(await file.arrayBuffer());if(!validImage(bytes,file.type))return apiError("SCREENSHOT_INVALID","This file is not a valid JPEG, PNG, or WebP screenshot.",400);attributes=await vision(bytes,file.type);if(!attributes)return auth.applyCookies(apiError("SHOPPING_ANALYSIS_UNAVAILABLE","Shopping analysis needs the configured private vision service.",503,true));const id=crypto.randomUUID();screenshot_path=`${auth.user.id}/${id}.${file.type.split("/")[1]}`;const upload=await auth.supabase.storage.from("shopping-screenshots").upload(screenshot_path,bytes,{contentType:file.type});if(upload.error)return auth.applyCookies(apiError("SCREENSHOT_UPLOAD_FAILED","The screenshot could not be stored privately.",500,true));}
  if(!attributes)return apiError("SHOPPING_ATTRIBUTES_INVALID","The product attributes could not be confirmed.",422);
  const [garments,profile,signals]=await Promise.all([loadGarments(auth.supabase,auth.user.id),loadProfile(auth.supabase,auth.user.id),loadWearSignals(auth.supabase,auth.user.id)]);const analysis=analyzeShoppingCandidate({candidate:attributes,garments,profile:profile.engine,signals,context:fallbackContext()});
  const row=await auth.supabase.from("shopping_analyses").insert({user_id:auth.user.id,screenshot_path,status:"completed",attributes_json:attributes,confidence:attributes.confidence,duplicate_score:analysis.duplicateScore,decision:analysis.decision,fills_gap:analysis.fillsGap,strong_outfit_count:analysis.strongOutfitCount,rationale:analysis.rationale}).select().single();if(row.error){if(screenshot_path)await auth.supabase.storage.from("shopping-screenshots").remove([screenshot_path]);return auth.applyCookies(apiError("SHOPPING_SAVE_FAILED","The shopping decision could not be saved.",500,true));}
  if(analysis.closestMatches.length)await auth.supabase.from("shopping_matches").insert(analysis.closestMatches.map(match=>({analysis_id:row.data.id,garment_id:match.garmentId,similarity:match.score,reasons_json:match.reasons})));
  await auth.supabase.from("product_events").insert({user_id:auth.user.id,event_name:"shopping_analyzed",properties_json:{decision:analysis.decision,strongOutfitCount:analysis.strongOutfitCount}});
  return auth.applyCookies(privateResponse({analysis:{...row.data,...analysis,attributes}},{status:201}));
}
