export type Category = "Tops" | "Bottoms" | "Dresses" | "Outerwear" | "Shoes";

export type Garment = {
  id: string;
  name: string;
  brand: string;
  category: Category;
  subcategory: string;
  color: string;
  material: string;
  warmth: number;
  formality: number;
  seasons: string[];
  occasions: string[];
  rainCompatible: boolean;
  image: string;
  inventoryType: "sample" | "owned";
  laundry: boolean;
  active: boolean;
  worn: number;
  lastWorn?: string;
  learnedFrom?: "scan" | "manual";
  confidence?: number;
  scanCount?: number;
};

export type Look = {
  id: string;
  label: string;
  title: string;
  reason: string;
  note: string;
  garmentIds: string[];
  warmth: number;
  formality: number;
  walking: string;
};

const asset = (name: string) => `/assets/garments/${name}.webp`;
const item = (
  id: string,
  name: string,
  category: Category,
  subcategory: string,
  color: string,
  material: string,
  warmth: number,
  formality: number,
  image: string,
  occasions: string[],
  worn: number,
  lastWorn?: string,
): Garment => ({
  id,
  name,
  brand: "Starter Closet",
  category,
  subcategory,
  color,
  material: `${material} · inferred`,
  warmth,
  formality,
  seasons:
    warmth >= 4
      ? ["Fall", "Winter"]
      : warmth <= 1
        ? ["Spring", "Summer"]
        : ["Spring", "Fall", "Winter"],
  occasions,
  rainCompatible: category !== "Shoes" || subcategory !== "Suede",
  image,
  inventoryType: "sample",
  laundry: false,
  active: true,
  worn,
  lastWorn,
});

export const starterCloset: Garment[] = [
  item(
    "g01",
    "Oatmeal Merino Crew",
    "Tops",
    "Sweater",
    "Oatmeal",
    "Merino wool",
    3,
    3,
    asset("oatmeal-merino-crew"),
    ["Office", "Casual", "Dinner"],
    7,
    "Aug 18",
  ),
  item(
    "g02",
    "Blue Relaxed Oxford",
    "Tops",
    "Button-down",
    "Pale blue",
    "Cotton",
    2,
    3,
    asset("blue-relaxed-oxford"),
    ["Office", "Casual"],
    5,
    "Aug 12",
  ),
  item(
    "g03",
    "Moss Fine-Knit Polo",
    "Tops",
    "Polo knit",
    "Moss",
    "Wool blend",
    3,
    4,
    asset("moss-knit-polo"),
    ["Office", "Dinner"],
    2,
    "Jul 28",
  ),
  item(
    "g04",
    "Effortless Trouser",
    "Bottoms",
    "Tailored trouser",
    "Charcoal",
    "Crepe",
    2,
    4,
    asset("charcoal-tailored-trouser"),
    ["Office", "Dinner"],
    8,
    "Aug 18",
  ),
  item(
    "g05",
    "Mason Wide Trouser",
    "Bottoms",
    "Wide-leg trouser",
    "Ivory",
    "TENCEL blend",
    2,
    4,
    asset("ivory-wide-trouser"),
    ["Office", "Dinner", "Travel"],
    3,
    "Jul 30",
  ),
  item(
    "g06",
    "Fluid Trench",
    "Outerwear",
    "Trench coat",
    "Stone",
    "Cotton blend",
    3,
    4,
    asset("stone-fluid-trench"),
    ["Office", "Casual", "Travel"],
    6,
    "Aug 18",
  ),
  item(
    "g07",
    "Cognac Penny Loafer",
    "Shoes",
    "Loafer",
    "Cognac",
    "Leather",
    1,
    4,
    asset("cognac-penny-loafer"),
    ["Office", "Dinner"],
    11,
    "Aug 18",
  ),
  item(
    "g08",
    "Chocolate Ballet Flat",
    "Shoes",
    "Flat",
    "Chocolate",
    "Leather",
    1,
    3,
    asset("chocolate-ballet-flat"),
    ["Office", "Dinner", "Casual"],
    7,
    "Aug 20",
  ),
  item(
    "g09",
    "Minimal White Sneaker",
    "Shoes",
    "Sneaker",
    "White",
    "Leather",
    1,
    2,
    asset("white-minimal-sneaker"),
    ["Casual", "Travel", "WFH"],
    14,
    "Aug 23",
  ),
  item(
    "g10",
    "Long-Sleeve Column",
    "Dresses",
    "Column dress",
    "Black",
    "Jersey",
    3,
    4,
    asset("black-column-dress"),
    ["Office", "Dinner"],
    1,
    "Jun 12",
  ),
  item(
    "g11",
    "Cropped Leather Jacket",
    "Outerwear",
    "Jacket",
    "Espresso",
    "Leather",
    3,
    4,
    asset("espresso-leather-jacket"),
    ["Dinner", "Date", "Casual"],
    4,
    "Aug 1",
  ),
  item(
    "g12",
    "Champagne Slip Dress",
    "Dresses",
    "Midi dress",
    "Champagne",
    "Satin",
    1,
    5,
    asset("champagne-slip-dress"),
    ["Dinner", "Event", "Date"],
    2,
    "Jul 19",
  ),
  item(
    "g13",
    "Cobalt Draped Midi",
    "Dresses",
    "One-shoulder midi",
    "Cobalt",
    "Satin crepe",
    1,
    5,
    asset("cobalt-draped-midi"),
    ["Wedding Guest", "Event", "Dinner"],
    0,
  ),
  item(
    "g14",
    "Bronze Strappy Sandal",
    "Shoes",
    "Low block heel",
    "Bronze",
    "Metallic leather",
    1,
    5,
    asset("bronze-strappy-sandal"),
    ["Wedding Guest", "Event", "Dinner"],
    0,
  ),
  item(
    "g15",
    "Berry Slingback Pump",
    "Shoes",
    "Kitten heel",
    "Berry",
    "Satin",
    1,
    5,
    asset("berry-slingback-pump"),
    ["Wedding Guest", "Event", "Dinner"],
    0,
  ),
  item(
    "g16",
    "Black Pointed Stiletto",
    "Shoes",
    "Stiletto pump",
    "Black",
    "Polished leather",
    1,
    5,
    asset("black-pointed-stiletto"),
    ["Office", "Date", "Dinner", "Event"],
    0,
  ),
  item(
    "g17",
    "Gold Ankle-Strap Heel",
    "Shoes",
    "High-heel sandal",
    "Champagne gold",
    "Metallic leather",
    1,
    5,
    asset("gold-ankle-strap-heel"),
    ["Wedding Guest", "Date", "Dinner", "Event"],
    0,
  ),
  item(
    "g18",
    "Ivory Pearl Slingback",
    "Shoes",
    "Kitten heel",
    "Ivory",
    "Satin",
    1,
    5,
    asset("ivory-pearl-slingback"),
    ["Wedding Guest", "Date", "Dinner", "Event"],
    0,
  ),
  item(
    "g19",
    "Ivory Bow Blouse",
    "Tops",
    "Silk tie-neck blouse",
    "Ivory",
    "Silk charmeuse",
    1,
    4,
    asset("ivory-bow-blouse"),
    ["Office", "Date", "Dinner", "Event"],
    0,
  ),
  item(
    "g20",
    "Blush Pleated Midi",
    "Bottoms",
    "Pleated midi skirt",
    "Blush",
    "Georgette",
    1,
    4,
    asset("blush-pleated-midi-skirt"),
    ["Office", "Date", "Dinner", "Wedding Guest"],
    0,
  ),
  item(
    "g21",
    "Dusty-Rose Wrap Midi",
    "Dresses",
    "Wrap midi dress",
    "Dusty rose",
    "Silk crepe",
    1,
    5,
    asset("dusty-rose-wrap-midi"),
    ["Date", "Dinner", "Wedding Guest", "Event"],
    0,
  ),
  item(
    "g22",
    "Navy Floral Tea Midi",
    "Dresses",
    "Floral tea dress",
    "Navy floral",
    "Crepe",
    1,
    4,
    asset("navy-floral-tea-midi"),
    ["Brunch", "Date", "Wedding Guest", "Event"],
    0,
  ),
];

export const recommendations: Look[] = [
  {
    id: "look-1",
    label: "Best overall",
    title: "Soft tailoring, two ways",
    reason:
      "A calm office base with enough polish for dinner, without needing a full change.",
    note: "Bring the trench — it will feel closer to 59° after sunset.",
    garmentIds: ["g01", "g04", "g06", "g07"],
    warmth: 4,
    formality: 4,
    walking: "All-day comfort",
  },
  {
    id: "look-2",
    label: "Most polished",
    title: "Moss knit + ivory trouser",
    reason:
      "The tonal contrast reads considered in the office and carries easily into dinner.",
    note: "A light layer handles the breezy commute.",
    garmentIds: ["g03", "g05", "g06", "g08"],
    warmth: 3,
    formality: 5,
    walking: "Comfortable commute",
  },
  {
    id: "look-3",
    label: "Most comfortable",
    title: "Oxford + relaxed tailoring",
    reason:
      "Easy all day, with the leather layer adding enough structure for evening.",
    note: "Breathable by noon, covered after sunset.",
    garmentIds: ["g02", "g04", "g11", "g09"],
    warmth: 3,
    formality: 3,
    walking: "Best for walking",
  },
  {
    id: "look-4",
    label: "Feminine polish",
    title: "Ivory bow + blush pleats",
    reason:
      "Soft movement and a defined waist make the look feel feminine without losing office polish.",
    note: "The pearl slingback keeps it dressy and walkable.",
    garmentIds: ["g19", "g20", "g06", "g18"],
    warmth: 2,
    formality: 5,
    walking: "Walkable kitten heel",
  },
];

export const weddingGuestLooks: Look[] = [
  {
    id: "wedding-1",
    label: "Ceremony to dance floor",
    title: "Champagne satin + bronze",
    reason:
      "Warm metallics feel celebratory while the low block heel stays comfortable through the reception.",
    note: "Add the trench only if the ceremony runs cool.",
    garmentIds: ["g12", "g14"],
    warmth: 1,
    formality: 5,
    walking: "Dance-floor ready",
  },
  {
    id: "wedding-2",
    label: "Color moment",
    title: "Cobalt drape + berry heel",
    reason:
      "A confident jewel-tone pairing that photographs beautifully without competing with the wedding party.",
    note: "The kitten heel keeps the silhouette refined and walkable.",
    garmentIds: ["g13", "g15"],
    warmth: 1,
    formality: 5,
    walking: "Comfortable heel",
  },
  {
    id: "wedding-3",
    label: "Evening wedding",
    title: "Black column + bronze",
    reason:
      "A clean evening base with a warm metallic shoe that keeps the look festive rather than severe.",
    note: "Layer the cropped leather jacket after dinner.",
    garmentIds: ["g10", "g11", "g14"],
    warmth: 3,
    formality: 5,
    walking: "Stable low heel",
  },
  {
    id: "wedding-4",
    label: "Romantic ceremony",
    title: "Dusty rose + pearl",
    reason:
      "The wrap shape and soft rose tone feel feminine and occasion-ready without becoming overly formal.",
    note: "The pearl slingback gives the dress a light, polished finish.",
    garmentIds: ["g21", "g18"],
    warmth: 1,
    formality: 5,
    walking: "Easy kitten heel",
  },
  {
    id: "wedding-5",
    label: "Garden celebration",
    title: "Navy floral + gold",
    reason:
      "A small floral print brings personality while the gold heel gives it a clean evening finish.",
    note: "Comfortable enough for the ceremony and reception.",
    garmentIds: ["g22", "g17"],
    warmth: 1,
    formality: 4,
    walking: "Event heel",
  },
];

export const week = [
  {
    day: "MON",
    date: "24",
    context: "Office",
    high: 68,
    low: 54,
    icon: "cloud",
    lookId: "look-2",
  },
  {
    day: "TUE",
    date: "25",
    context: "Office → Dinner",
    high: 67,
    low: 59,
    icon: "wind",
    lookId: "look-1",
    active: true,
  },
  {
    day: "WED",
    date: "26",
    context: "WFH",
    high: 73,
    low: 61,
    icon: "sun",
    lookId: "look-3",
  },
  {
    day: "THU",
    date: "27",
    context: "Office",
    high: 62,
    low: 51,
    icon: "rain",
    lookId: "look-2",
  },
  {
    day: "FRI",
    date: "28",
    context: "Travel",
    high: 71,
    low: 57,
    icon: "cloud",
  },
  {
    day: "SAT",
    date: "29",
    context: "Dinner",
    high: 76,
    low: 62,
    icon: "sun",
    lookId: "look-3",
  },
  { day: "SUN", date: "30", context: "Casual", high: 70, low: 55, icon: "sun" },
];

export const demoHistory = [
  {
    id: "h1",
    date: "Monday, Aug 17",
    context: "Office",
    temp: "64° · Breezy",
    feedback: "Loved it · Just right",
    look: recommendations[1],
  },
  {
    id: "h2",
    date: "Saturday, Aug 15",
    context: "Dinner",
    temp: "71° · Clear",
    feedback: "Loved it · Just right",
    look: recommendations[0],
  },
  {
    id: "h3",
    date: "Thursday, Aug 13",
    context: "WFH + Errands",
    temp: "76° · Sunny",
    feedback: "Loved it · Too warm",
    look: recommendations[2],
  },
];
