import { loadGarments } from "../../../../lib/pilot-server";
import { apiError, privateResponse, requireUser, unauthorized } from "../../../../lib/supabase-server";

const categories=new Set(["Tops","Bottoms","Dresses","Outerwear","Shoes"]);
const dataImage=(value:string)=>{const match=value.match(/^data:image\/(jpeg|png|webp);base64,(.+)$/);if(!match)throw new Error("IMAGE_INVALID");const bytes=Uint8Array.from(atob(match[2]),character=>character.charCodeAt(0));if(bytes.byteLength>12*1024*1024)throw new Error("IMAGE_TOO_LARGE");return{bytes,type:`image/${match[1]}`};};

export async function GET(request:Request){const auth=await requireUser(request);if(!auth)return unauthorized();try{return auth.applyCookies(privateResponse({items:await loadGarments(auth.supabase,auth.user.id)}));}catch{return auth.applyCookies(apiError("WARDROBE_READ_FAILED","Your closet could not be loaded.",500,true));}}

export async function POST(request:Request){
  const auth=await requireUser(request);if(!auth)return unauthorized();const body=await request.json().catch(()=>({})) as Record<string,unknown>;const category=String(body.category||"");if(!categories.has(category))return apiError("GARMENT_CATEGORY_INVALID","Choose a garment category.",400);
  let image_path:string|null=null;
  if(body.imageData){try{const image=dataImage(String(body.imageData));const imageId=crypto.randomUUID();image_path=`${auth.user.id}/${imageId}.webp`;const upload=await auth.supabase.storage.from("garments").upload(image_path,image.bytes,{contentType:image.type,upsert:false});if(upload.error)throw upload.error;}catch{return auth.applyCookies(apiError("GARMENT_IMAGE_INVALID","Use a JPEG, PNG, or WebP image under 12 MB.",400));}}
  const row={id:crypto.randomUUID(),user_id:auth.user.id,name:String(body.name||`${body.color||""} ${body.subcategory||category}`).trim().slice(0,100),brand:String(body.brand||"My Closet").slice(0,80),category,subcategory:String(body.subcategory||category).slice(0,60),color:String(body.color||"Neutral").slice(0,40),material:String(body.material||"Material to confirm").slice(0,80),material_confidence:"inferred",warmth_score:Math.max(1,Math.min(5,Number(body.warmth)||2)),formality_score:Math.max(1,Math.min(5,Number(body.formality)||3)),seasons:Array.isArray(body.seasons)?body.seasons.slice(0,4):[],occasions:Array.isArray(body.occasions)?body.occasions.slice(0,8):[],rain_compatible:Boolean(body.rainCompatible),image_path,inventory_type:"owned",laundry_status:false,active:true,source:String(body.source||"manual")};
  const result=await auth.supabase.from("garments").insert(row).select().single();if(result.error){if(image_path)await auth.supabase.storage.from("garments").remove([image_path]);return auth.applyCookies(apiError("GARMENT_SAVE_FAILED","This item could not be added.",500,true));}return auth.applyCookies(privateResponse({item:result.data},{status:201}));
}

export async function PATCH(request:Request){const auth=await requireUser(request);if(!auth)return unauthorized();const body=await request.json().catch(()=>({})) as Record<string,unknown>;const id=String(body.id||"");if(!id)return apiError("GARMENT_ID_REQUIRED","Item ID is required.",400);const changes:Record<string,unknown>={updated_at:new Date().toISOString()};if(typeof body.laundry==="boolean")changes.laundry_status=body.laundry;if(typeof body.active==="boolean")changes.active=body.active;if(body.name)changes.name=String(body.name).slice(0,100);const result=await auth.supabase.from("garments").update(changes).eq("id",id).eq("user_id",auth.user.id).select().maybeSingle();return auth.applyCookies(result.error?apiError("GARMENT_UPDATE_FAILED","This item could not be updated.",500,true):privateResponse({item:result.data}));}

export async function DELETE(request:Request){const auth=await requireUser(request);if(!auth)return unauthorized();const id=new URL(request.url).searchParams.get("id");if(!id)return apiError("GARMENT_ID_REQUIRED","Item ID is required.",400);const {data}=await auth.supabase.from("garments").select("image_path").eq("id",id).eq("user_id",auth.user.id).maybeSingle();if(!data)return auth.applyCookies(privateResponse({ok:true}));if(data.image_path){const removed=await auth.supabase.storage.from("garments").remove([data.image_path]);if(removed.error)return auth.applyCookies(apiError("GARMENT_DELETE_PENDING","The image could not be removed yet.",503,true));}const result=await auth.supabase.from("garments").delete().eq("id",id).eq("user_id",auth.user.id);return auth.applyCookies(result.error?apiError("GARMENT_DELETE_FAILED","This item could not be removed.",500,true):privateResponse({ok:true}));}
