alter table public.profiles add column if not exists profile_version integer not null default 1;
alter table public.garments add column if not exists pattern text;
alter table public.garments add column if not exists silhouette text;
alter table public.garments add column if not exists source text not null default 'manual';
alter table public.garments add column if not exists source_hash text;
alter table public.garments add column if not exists perceptual_hash text;
alter table public.garments add column if not exists duplicate_of uuid references public.garments(id) on delete set null;
alter table public.garments add column if not exists metadata_version integer not null default 1;
alter table public.garments add column if not exists confidence numeric(4,3);
alter table public.garments add column if not exists worn_count integer not null default 0;
alter table public.garments add column if not exists last_worn date;

drop index if exists wardrobe_items_user_fingerprint_idx;
create unique index if not exists garments_user_source_hash_idx on public.garments(user_id,source_hash) where source_hash is not null;
create index if not exists garments_user_perceptual_hash_idx on public.garments(user_id,perceptual_hash) where perceptual_hash is not null;

alter table public.recommendations add column if not exists engine_version text not null default 'owned_closet_v1';
alter table public.recommendations add column if not exists context_hash text;
alter table public.recommendations add column if not exists score numeric(5,2);
alter table public.recommendations add column if not exists factors_json jsonb not null default '{}'::jsonb;
alter table public.recommendations add column if not exists selected_at timestamptz;
alter table public.wear_history add column if not exists outfit_snapshot_json jsonb not null default '{}'::jsonb;
alter table public.wear_history add column if not exists try_on_result_id uuid references public.try_on_results(id) on delete set null;
alter table public.try_on_jobs add column if not exists garment_ids uuid[] not null default array[]::uuid[];
alter table public.try_on_jobs add column if not exists reference_photo_id uuid references public.person_reference_photos(id) on delete set null;
alter table public.try_on_results add column if not exists board_json jsonb not null default '{}'::jsonb;
alter table public.try_on_results add column if not exists expires_at timestamptz;
alter table public.person_reference_photos add column if not exists deleted_at timestamptz;

create table if not exists public.shopping_analyses (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  screenshot_path text, thumbnail_path text, status text not null default 'processing' check(status in ('processing','completed','failed','deleted')),
  attributes_json jsonb not null default '{}'::jsonb, confidence numeric(4,3), duplicate_score numeric(4,3),
  decision text check(decision in ('buy','save','skip')), fills_gap boolean, strong_outfit_count integer not null default 0,
  rationale text, saved boolean not null default false, expires_at timestamptz not null default now()+interval '24 hours',
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.shopping_matches (
  analysis_id uuid not null references public.shopping_analyses(id) on delete cascade,
  garment_id uuid not null references public.garments(id) on delete cascade,
  similarity numeric(4,3) not null, reasons_json jsonb not null default '[]'::jsonb,
  primary key(analysis_id,garment_id)
);
create table if not exists public.calendar_oauth_states (
  state_hash text primary key, user_id uuid not null references auth.users(id) on delete cascade,
  expires_at timestamptz not null, created_at timestamptz not null default now()
);
create table if not exists public.deletion_requests (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null, target_id uuid, object_paths_json jsonb not null default '[]'::jsonb,
  status text not null default 'pending' check(status in ('pending','processing','completed','failed')),
  attempts integer not null default 0, error_code text, completed_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.product_events (
  id bigint generated by default as identity primary key, user_id uuid references auth.users(id) on delete set null,
  event_name text not null, properties_json jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create table if not exists public.local_migrations (
  user_id uuid not null references auth.users(id) on delete cascade, payload_hash text not null,
  imported_at timestamptz not null default now(), primary key(user_id,payload_hash)
);

create index if not exists shopping_analyses_user_created_idx on public.shopping_analyses(user_id,created_at desc);
create index if not exists deletion_requests_user_status_idx on public.deletion_requests(user_id,status,created_at);
create index if not exists product_events_name_created_idx on public.product_events(event_name,created_at desc);

alter table public.shopping_analyses enable row level security;
alter table public.shopping_matches enable row level security;
alter table public.calendar_oauth_states enable row level security;
alter table public.deletion_requests enable row level security;
alter table public.product_events enable row level security;
alter table public.local_migrations enable row level security;

create policy "shopping analyses owned" on public.shopping_analyses for all to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
create policy "shopping matches owned" on public.shopping_matches for all to authenticated using(exists(select 1 from public.shopping_analyses a where a.id=analysis_id and a.user_id=(select auth.uid()))) with check(exists(select 1 from public.shopping_analyses a where a.id=analysis_id and a.user_id=(select auth.uid())));
create policy "calendar oauth states owned" on public.calendar_oauth_states for all to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
create policy "deletion requests owned" on public.deletion_requests for select to authenticated using((select auth.uid())=user_id);
create policy "deletion requests insert own" on public.deletion_requests for insert to authenticated with check((select auth.uid())=user_id);
create policy "deletion requests update own" on public.deletion_requests for update to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
create policy "product events insert own" on public.product_events for insert to authenticated with check((select auth.uid())=user_id);
create policy "local migrations owned" on public.local_migrations for all to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);

grant select,insert,update,delete on public.shopping_analyses,public.shopping_matches,public.calendar_oauth_states,public.deletion_requests,public.local_migrations to authenticated;
grant insert on public.product_events to authenticated;
revoke all on public.shopping_analyses,public.shopping_matches,public.calendar_oauth_states,public.deletion_requests,public.product_events,public.local_migrations from anon;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values
  ('shopping-screenshots','shopping-screenshots',false,10485760,array['image/jpeg','image/png','image/webp']),
  ('garments','garments',false,12582912,array['image/jpeg','image/png','image/webp']),
  ('person-reference-photos','person-reference-photos',false,12582912,array['image/jpeg','image/png','image/webp']),
  ('try-on-results','try-on-results',false,12582912,array['image/png','image/webp'])
on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

create policy "shopping screenshots owned select" on storage.objects for select to authenticated using(bucket_id='shopping-screenshots' and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy "shopping screenshots owned insert" on storage.objects for insert to authenticated with check(bucket_id='shopping-screenshots' and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy "shopping screenshots owned delete" on storage.objects for delete to authenticated using(bucket_id='shopping-screenshots' and (storage.foldername(name))[1]=(select auth.uid())::text);
